"""create_iris_table

Revision ID: 43e495057c67
Revises: 
Create Date: 2026-05-19 11:10:41.318183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e495057c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Iris',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SepalLengthCm', sa.Float(), nullable=False),
    sa.Column('SepalWidthCm', sa.Float(), nullable=False),
    sa.Column('PetalLengthCm', sa.Float(), nullable=False),
    sa.Column('PetalWidthCm', sa.Float(), nullable=False),
    sa.Column('Species', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_Iris_Id'), 'Iris', ['Id'], unique=False)
    op.create_index(op.f('ix_Iris_Species'), 'Iris', ['Species'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Iris_Species'), table_name='Iris')
    op.drop_index(op.f('ix_Iris_Id'), table_name='Iris')
    op.drop_table('Iris')
    # ### end Alembic commands ###
